### ISSUE TITLE
Export coverage value as GitHub Action Output

### ISSUE THREAD

**Issue by emibcn** [johanvanhelden/clover-coverage-check#1]
Hello!

It would be great to access the calculated value as an aoutput value os the action. It just needs to `echo` in a fancy way, something like:

```php
echo '##[set-output name=elements;]' . $coverage . PHP_EOL;
```

Then, this number can be used from next actions, with something like:

```yaml
- name: Check test coverage
  uses: johanvanhelden/gha-clover-test-coverage-check@v1
  id: coverage
  with:
    percentage: "95"
    filename: "coverage.xml"

# Use the output from the `coverage` step
- name: Generate the badge SVG image
  uses: emibcn/badge-action@v1
  id: badge
  with:
    label: 'Coverage'
    status: ${{ steps.coverage.outputs.elements }}
    color: ${{ steps.coverage.outputs.elements > 95 && 'green' || 'red' }}
    path: ./badges/test-coverage.svg
```
