### ISSUE TITLE
Round decimals in a new output value

### ISSUE THREAD

**Issue by emibcn** [johanvanhelden/clover-coverage-check#5]
Hello again!

It would be nice to tell to the action a maximum number of decimals to show in an output value. Now, I have to add an extra action to round it, when it will be often needed. I think an extra output value its better than the original one, as rounding up may loose desired precision:

```php
$precision = (int) $argv[3];

# [...]

echo '##[set-output name=round;]' . round($coverage, $precision) . PHP_EOL;
```

And then, in `action.yml`:
```yml
inputs:
#[...]
  precision:
    description: "The precision of the rounded value."
    required: true
    default: "2"
#[...]
outputs:
#[...]
  round:
    description: 'The processed value from the XML file, rounded to `precision` decimals.'
#[...]
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.percentage }}
    - ${{ inputs.precision }}
```
